"""create codeforces profiles table

Revision ID: 57d91b2bf37b
Revises: cd5f40affddd
Create Date: 2026-06-04 08:23:36.892857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d91b2bf37b'
down_revision: Union[str, Sequence[str], None] = 'cd5f40affddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codeforces_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('max_rating', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=100), nullable=False),
    sa.Column('max_rank', sa.String(length=100), nullable=False),
    sa.Column('contribution', sa.Integer(), nullable=False),
    sa.Column('friend_count', sa.Integer(), nullable=False),
    sa.Column('codeforces_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codeforces_profiles')
    # ### end Alembic commands ###
